### ISSUE TITLE
CSS todo

### ISSUE THREAD

**Issue by abrahamjuliot** [abrahamjuliot/creepjs#4]
- [x] reset
- [x] mobile first layout (grid or flex)
- [x] css modal to view details
- [x] screen animation
- [x] version icons
- [ ] timezone globe animation
- [ ] math animation
- [ ] error animation
